# fly.toml app configuration file generated for octo-grafana on 2024-07-25T10:26:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'octo-grafana'
primary_region = 'iad'

[build]
  image = 'grafana/grafana:11.1.1'

[env]
  GF_INSTALL_PLUGINS = 'grafana-worldmap-panel,grafana-clock-panel'

[[mounts]]
  source = 'grafana_storage'
  destination = '/var/lib/grafana'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/login'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
