<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Interfold.Tags.Contracts\Interfold.Tags.Contracts.csproj" />
    <ProjectReference Include="..\Interfold.Contracts\Interfold.Contracts.csproj" />
    <ProjectReference Include="..\Interfold.Domain\Interfold.Domain.csproj" />
  </ItemGroup>
</Project>
