namespace Interfold.DatabaseBootstrap;

/// <summary>Input contract for <see cref="PostgresSeeder.BootstrapAsync"/>. Populated
/// from <c>BootstrapConfig</c> + <c>GeneratedSecrets</c> in production and hand-fed
/// deterministic constants by test fixtures.</summary>
/// <param name="InitUser">initdb bootstrap superuser (hard-coded <c>db_init</c>).</param>
/// <param name="InitPassword">Password for <see cref="InitUser"/> during the seed run.</param>
/// <param name="AppUser">App role — <c>NOSUPERUSER NOCREATEDB NOCREATEROLE</c>; the only
/// role in the compose connection string.</param>
/// <param name="AppPassword">Password for <see cref="AppUser"/>.</param>
/// <param name="AdminUser">Admin role (<c>SUPERUSER</c>); owns the app database and the
/// <c>internal</c> schema.</param>
/// <param name="AdminPassword">Password for <see cref="AdminUser"/>.</param>
/// <param name="DefaultDatabase">Application database, owned by the admin role.
/// Defaults to <c>interfold</c>; overridable for shared clusters.</param>
/// <param name="GoogleOAuthClientSecret">Seeded as <c>oauth:google:client_secret</c>.
/// Empty values skip the row.</param>
/// <param name="DiscordOAuthClientSecret">Seeded as <c>oauth:discord:client_secret</c>.</param>
/// <param name="AppleOAuthClientSecret">Seeded as <c>oauth:apple:client_secret</c>.</param>
/// <param name="EncryptionPepper">Seeded as <c>encryption:pepper</c>.</param>
/// <param name="ScyllaContactPoints">Seeded as <c>scylla:contact_points</c>.</param>
/// <param name="ScyllaLocalDatacenter">Seeded as <c>scylla:local_datacenter</c>.</param>
/// <param name="ScyllaAppUser">Seeded as <c>scylla:username</c>; matches the app user
/// that <see cref="ScyllaSeeder"/> creates on the same run.</param>
/// <param name="ScyllaAppPassword">Seeded as <c>scylla:password</c>.</param>
/// <param name="ScyllaPort">Seeded as <c>scylla:port</c>.</param>
/// <param name="ScyllaAdminUser">Seeded as <c>scylla:admin_username</c>; consumed by
/// <c>ScyllaMigrationService</c> for keyspace-level DDL.</param>
/// <param name="ScyllaAdminPassword">Seeded as <c>scylla:admin_password</c>.</param>
/// <param name="JwtRsa256PrivateKeyPem">RSA-2048 JWT signing key (PEM, PKCS#8),
/// seeded as <c>auth:jwt_rsa256_private_pem</c>. No on-disk fallback in the API.</param>
/// <param name="JwtEs256PrivateKeyPem">ES256 JWT signing key (PEM, SEC1), seeded as
/// <c>auth:jwt_es256_private_pem</c>.</param>
/// <param name="DeepLinkSecret">HMAC secret for the phase-F deep-link exchange, seeded
/// as <c>auth:deep_link_secret</c>. Auto-generated by <c>SecretsPhase</c>.</param>
/// <param name="LeafPfxPassword">Password for the Kestrel leaf PFX, seeded as
/// <c>certs:leaf_pfx_password</c>.</param>
/// <param name="ScrambleInitUserPassword"><c>true</c> in production so the .env value
/// goes stale in-cluster after seeding; <c>false</c> in tests so idempotent retries
/// can still authenticate as db_init.</param>
/// <param name="FirebaseAndroidClientJson">Optional; seeded as
/// <c>firebase:client:android</c>. Null/empty skips the row and the matching endpoint
/// returns 503.</param>
/// <param name="FirebaseIosClientJson">Optional; seeded as <c>firebase:client:ios</c>.</param>
/// <param name="FirebaseWebClientJson">Optional; seeded as <c>firebase:client:web</c>.</param>
/// <param name="FcmServiceAccountJson">Optional Firebase FCM v1 service-account JSON,
/// seeded as <c>fcm:service_account_json</c>. Absent → the DI factory returns
/// <c>NullFCMService</c> so notifications no-op instead of erroring.</param>
public sealed record PostgresSeedOptions(
    string InitUser,
    string InitPassword,
    string AppUser,
    string AppPassword,
    string AdminUser,
    string AdminPassword,
    string DefaultDatabase,
    string GoogleOAuthClientSecret,
    string DiscordOAuthClientSecret,
    string AppleOAuthClientSecret,
    string EncryptionPepper,
    string ScyllaContactPoints,
    string ScyllaLocalDatacenter,
    string ScyllaAppUser,
    string ScyllaAppPassword,
    int ScyllaPort,
    string ScyllaAdminUser,
    string ScyllaAdminPassword,
    string JwtRsa256PrivateKeyPem,
    string JwtEs256PrivateKeyPem,
    string DeepLinkSecret,
    string LeafPfxPassword,
    bool ScrambleInitUserPassword,
    string? FirebaseAndroidClientJson = null,
    string? FirebaseIosClientJson = null,
    string? FirebaseWebClientJson = null,
    string? FcmServiceAccountJson = null);
